# Étape 1 : Build Angular
FROM node:18 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build --prod

# Étape 2 : Serveur Nginx
FROM nginx:alpine

# Copier le build Angular dans Nginx
COPY --from=build /app/dist/admin-temp /usr/share/nginx/html

# Copier un fichier de config Nginx personnalisé si besoin (facultatif)
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
